name 'chef_part2'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef_part2'
long_description 'Installs/Configures chef_part2'
version '0.1.0'
